/*
 * SINGLE FILE TEST SUITE HEADER MACRO LIB
 * **LIMITED TO 50 TESTS**
 */

#include <stdio.h>
#include <assert.h>

int tests_run;

#define TA()

#define CONCAT(a, b) a##b
#define MACCONCAT(a, b) CONCAT(a, b)
#define TESTFUNCRET int
#define TESTFUNCARGS (void)
#define TEST(name) TESTFUNCRET MACCONCAT(test_, __COUNTER__)TESTFUNCARGS {\
	printf("LINE %d: Running \"%s\" %d", __LINE__, name, tests_run);\
	tests_run++;

#define TEND() puts(" ... passed");\
	return 0;\
}


#define TDELIM ,
#define TESTFUNC0
#define TESTFUNC1 test_0
#define TESTFUNC2 TDELIM TESTFUNC1 test_1
#define TESTFUNC3 TDELIM TESTFUNC2 test_2
#define TESTFUNC4 TDELIM TESTFUNC3 test_3
#define TESTFUNC5 TDELIM TESTFUNC4 test_4
#define TESTFUNC6 TDELIM TESTFUNC5 test_5
#define TESTFUNC7 TDELIM TESTFUNC6 test_6
#define TESTFUNC8 TDELIM TESTFUNC7 test_7
#define TESTFUNC9 TDELIM TESTFUNC8 test_8
#define TESTFUNC10 TDELIM TESTFUNC9 test_9
#define TESTFUNC11 TDELIM TESTFUNC10 test_10
#define TESTFUNC12 TDELIM TESTFUNC11 test_11
#define TESTFUNC13 TDELIM TESTFUNC12 test_12
#define TESTFUNC14 TDELIM TESTFUNC13 test_13
#define TESTFUNC15 TDELIM TESTFUNC14 test_14
#define TESTFUNC16 TDELIM TESTFUNC15 test_15
#define TESTFUNC17 TDELIM TESTFUNC16 test_16
#define TESTFUNC18 TDELIM TESTFUNC17 test_17
#define TESTFUNC19 TDELIM TESTFUNC18 test_18
#define TESTFUNC20 TDELIM TESTFUNC19 test_19
#define TESTFUNC21 TDELIM TESTFUNC20 test_20
#define TESTFUNC22 TDELIM TESTFUNC21 test_21
#define TESTFUNC23 TDELIM TESTFUNC22 test_22
#define TESTFUNC24 TDELIM TESTFUNC23 test_23
#define TESTFUNC25 TDELIM TESTFUNC24 test_24
#define TESTFUNC26 TDELIM TESTFUNC25 test_25
#define TESTFUNC27 TDELIM TESTFUNC26 test_26
#define TESTFUNC28 TDELIM TESTFUNC27 test_27
#define TESTFUNC29 TDELIM TESTFUNC28 test_28
#define TESTFUNC30 TDELIM TESTFUNC29 test_29
#define TESTFUNC31 TDELIM TESTFUNC30 test_30
#define TESTFUNC32 TDELIM TESTFUNC31 test_31
#define TESTFUNC33 TDELIM TESTFUNC32 test_32
#define TESTFUNC34 TDELIM TESTFUNC33 test_33
#define TESTFUNC35 TDELIM TESTFUNC34 test_34
#define TESTFUNC36 TDELIM TESTFUNC35 test_35
#define TESTFUNC37 TDELIM TESTFUNC36 test_36
#define TESTFUNC38 TDELIM TESTFUNC37 test_37
#define TESTFUNC39 TDELIM TESTFUNC38 test_38
#define TESTFUNC40 TDELIM TESTFUNC39 test_39
#define TESTFUNC41 TDELIM TESTFUNC40 test_40
#define TESTFUNC42 TDELIM TESTFUNC41 test_41
#define TESTFUNC43 TDELIM TESTFUNC42 test_42
#define TESTFUNC44 TDELIM TESTFUNC43 test_43
#define TESTFUNC45 TDELIM TESTFUNC44 test_44
#define TESTFUNC46 TDELIM TESTFUNC45 test_45
#define TESTFUNC47 TDELIM TESTFUNC46 test_46
#define TESTFUNC48 TDELIM TESTFUNC47 test_47
#define TESTFUNC49 TDELIM TESTFUNC48 test_48
#define TESTFUNC50 TDELIM TESTFUNC49 test_49

// #define EXPAND(...) __VA_ARGS__
#define TESTFUNGEN__(N) TESTFUNC##N
#define TESTFUNGEN_(N) TESTFUNGEN__(N)
#define TESTFUNGEN() TESTFUNGEN_(__COUNTER__)


/*
	Test format:
TEST("name")
	
TEND()
*/

